root: true
parser: "@typescript-eslint/parser"
parserOptions:
  tsconfigRootDir: . 
  project: ['./tsconfig.json', 'test/tsconfig.json']
env:
  node: true
plugins:
  - "@typescript-eslint"
  - prettier
extends:
  - plugin:eslint-comments/recommended
  - plugin:import/typescript
  - plugin:prettier/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
settings:
  import/resolver: typescript
overrides:
  - files:
    - 'test/**'
    plugins:
      - 'jest'
    extends:
      - plugin:jest/recommended
      - plugin:jest/style
    rules: 
      '@typescript-eslint/unbound-method': 'off'
      'jest/unbound-method': 'error'
rules:
  prettier/prettier: error
  import/export: off
  "@typescript-eslint/ban-types": error
  "@typescript-eslint/no-explicit-any": error
  "@typescript-eslint/explicit-member-accessibility": error
  "@typescript-eslint/explicit-module-boundary-types": error
  "@typescript-eslint/member-ordering": error
  "@typescript-eslint/no-namespace": off

