root: true
parser: "@typescript-eslint/parser"
parserOptions:
  tsconfigRootDir: .
  project: ['./tsconfig.json']
env:
  node: true
plugins:
  - "@typescript-eslint"
  - prettier
extends:
  - plugin:eslint-comments/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:node/recommended
  - plugin:prettier/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
settings:
  import/resolver: typescript
rules:
  prettier/prettier: error
