root: true
parser: "@typescript-eslint/parser"
parserOptions:
  tsconfigRootDir: .
  project: ['./tsconfig.json']
plugins:
  - "@typescript-eslint"
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:node/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
settings:
  import/resolver: typescript
env:
  node: true
